# Generated by Django 5.2.4 on 2025-07-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accreditation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlliedService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.CharField(default="Active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="BestTreatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("tagline", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_logos/"
                    ),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_covers/"
                    ),
                ),
                (
                    "year_established",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "license_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "visiting_hours",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "operating_hours",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("insurance_accepted", models.TextField(blank=True, null=True)),
                ("languages_spoken", models.TextField(blank=True, null=True)),
                (
                    "patient_capacity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("hospital_features", models.TextField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=10, null=True)),
                ("reviews", models.TextField(blank=True, null=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("parking_available", models.BooleanField(default=False)),
                ("parking_details", models.TextField(blank=True, null=True)),
                ("pharmacy_available", models.BooleanField(default=False)),
                ("blood_bank_available", models.BooleanField(default=False)),
                ("fax_number", models.CharField(blank=True, max_length=20, null=True)),
                ("state", models.CharField(blank=True, max_length=100, null=True)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("nearby_landmarks", models.TextField(blank=True, null=True)),
                ("map_location", models.TextField(blank=True, null=True)),
                ("latitude", models.CharField(blank=True, max_length=20, null=True)),
                ("longitude", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "primary_contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "secondary_contact_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "emergency_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "ambulance_contact",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("owned_by", models.CharField(blank=True, max_length=255, null=True)),
                ("ceo_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_bed_count",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("icu_beds_available", models.BooleanField(default=False)),
                (
                    "icu_beds_count",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("suite_rooms_available", models.BooleanField(default=False)),
                (
                    "suite_rooms_count",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("suite_room_details", models.TextField(blank=True, null=True)),
                ("vip_rooms_available", models.BooleanField(default=False)),
                (
                    "vip_rooms_count",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("vip_room_details", models.TextField(blank=True, null=True)),
                (
                    "emergency_casualty_beds",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("seo_title", models.CharField(blank=True, max_length=255, null=True)),
                ("meta_description", models.TextField(blank=True, null=True)),
                ("keywords", models.TextField(blank=True, null=True)),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("status", models.CharField(default="Active", max_length=20)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("award_date", models.DateField()),
                ("awarded_by", models.CharField(max_length=150)),
                ("award_type", models.CharField(blank=True, max_length=100)),
                ("location", models.CharField(blank=True, max_length=150)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital/awards/"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True, null=True, upload_to="hospital/awards/certificates/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HospitalGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("image", models.ImageField(upload_to="hospital/gallery/")),
                ("category", models.CharField(blank=True, max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("uploaded_by", models.CharField(blank=True, max_length=100)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HospitalType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_type_icons/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Specialty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="specialty_icons/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Specialties",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BestSurgeon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor_app.doctor",
                    ),
                ),
            ],
        ),
    ]
