# Generated by Django 5.2.4 on 2025-07-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospital_app", "0001_initial"),
        ("treatment_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="besttreatment",
            name="treatment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="treatment_app.treatment",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="accreditation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital_app.accreditation",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="allied_services",
            field=models.ManyToManyField(
                blank=True, related_name="hospitals", to="hospital_app.alliedservice"
            ),
        ),
        migrations.AddField(
            model_name="besttreatment",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="best_treatments",
                to="hospital_app.hospital",
            ),
        ),
        migrations.AddField(
            model_name="bestsurgeon",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="best_surgeons",
                to="hospital_app.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospitalaward",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="hospital_app.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospitalgallery",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="galleries",
                to="hospital_app.hospital",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="hospital_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hospital_app.hospitaltype",
            ),
        ),
        migrations.AddField(
            model_name="hospital",
            name="specialties",
            field=models.ManyToManyField(
                blank=True, related_name="hospitals", to="hospital_app.specialty"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="besttreatment",
            unique_together={("hospital", "treatment")},
        ),
        migrations.AlterUniqueTogether(
            name="bestsurgeon",
            unique_together={("hospital", "doctor")},
        ),
    ]
