# Generated by Django 5.2.4 on 2025-08-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospital",
            name="icu_beds_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="suite_rooms_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="total_bed_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="hospital",
            name="vip_rooms_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
