# Generated by Django 5.2.4 on 2025-08-01 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0003_alter_hospital_icu_beds_count_and_more"),
        ("treatment_app", "0002_treatment_treatment_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="besttreatment",
            name="treatment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="treatment_app.treatment",
            ),
        ),
    ]
