# Generated by Django 5.2.4 on 2025-08-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0004_alter_besttreatment_treatment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accreditation",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="accreditation",
            name="accreditation_type",
            field=models.CharField(
                choices=[
                    ("national", "National"),
                    ("international", "International"),
                    ("state", "State"),
                    ("specialty", "Specialty"),
                    ("quality", "Quality"),
                ],
                default="national",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="authority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="certificate_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="accreditation_documents/"
            ),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="renewal_reminder_days",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="valid_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="valid_to",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accreditation",
            name="website_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accreditation",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("expired", "Expired"),
                    ("pending", "Pending"),
                    ("suspended", "Suspended"),
                    ("revoked", "Revoked"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
