# Generated by Django 5.2.4 on 2025-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_app", "0005_rename_name_accreditation_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alliedservice",
            name="contact_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="duration_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="is_emergency_available",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="operating_hours",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="requires_appointment",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="alliedservice",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("laboratory", "Laboratory"),
                    ("radiology", "Radiology"),
                    ("pharmacy", "Pharmacy"),
                    ("physiotherapy", "Physiotherapy"),
                    ("nutrition", "Nutrition"),
                    ("counseling", "Counseling"),
                    ("transport", "Transport"),
                    ("housekeeping", "Housekeeping"),
                    ("security", "Security"),
                    ("maintenance", "Maintenance"),
                ],
                default="laboratory",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="alliedservice",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("maintenance", "Under Maintenance"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
