# Generated by Django 5.2.4 on 2025-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelpermission',
            name='can_read',
            field=models.BooleanField(default=False),
        ),
    ]
