# Generated by Django 5.2.4 on 2025-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital_review", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hospitalreview",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="hospitalreview",
            old_name="client_name",
            new_name="patient_name",
        ),
        migrations.RemoveField(
            model_name="hospitalreview",
            name="diagnosis",
        ),
        migrations.RemoveField(
            model_name="hospitalreview",
            name="image",
        ),
        migrations.AddField(
            model_name="hospitalreview",
            name="patient_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="patient_pictures/"
            ),
        ),
        migrations.AlterField(
            model_name="hospitalreview",
            name="rating",
            field=models.FloatField(default=0.0),
        ),
    ]
