# Generated by Django 5.2.4 on 2025-07-30 09:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor_app", "0001_initial"),
        ("hospital_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TreatmentCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="category_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="treatment_images/"
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=4.5, max_digits=3),
                ),
                (
                    "symptoms",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "precautions",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "risk_factors",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "preparations",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "procedure",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "post_procedure",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "success_rate",
                    django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
                ),
                (
                    "doctors",
                    models.ManyToManyField(
                        blank=True, related_name="treatments", to="doctor_app.doctor"
                    ),
                ),
                (
                    "hospitals",
                    models.ManyToManyField(
                        blank=True,
                        related_name="treatments",
                        to="hospital_app.hospital",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="treatments",
                        to="treatment_app.treatmentcategory",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="treatment_headers/"
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "treatment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="treatment_app.treatment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TreatmentIntro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("introduction", models.TextField(blank=True)),
                (
                    "before_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="treatment_intro/"
                    ),
                ),
                (
                    "after_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="treatment_intro/"
                    ),
                ),
                ("stay_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "duration_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "anesthesia_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cost_info", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "treatment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intro",
                        to="treatment_app.treatment",
                    ),
                ),
            ],
        ),
    ]
