# Generated by Django 5.2.4 on 2025-07-30 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="treatment_type",
            field=models.CharField(
                choices=[
                    ("surgery", "Surgery"),
                    ("therapy", "Therapy"),
                    ("consultation", "Consultation"),
                    ("diagnostic", "Diagnostic"),
                    ("emergency", "Emergency"),
                    ("preventive", "Preventive"),
                ],
                default="consultation",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="treatmentcategory",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
