# Generated by Django 5.2.4 on 2025-08-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment_app", "0002_treatment_treatment_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="treatmentcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
