# Generated by Django 5.2.4 on 2025-08-01 05:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("treatment_app", "0003_treatment_is_active_treatmentcategory_is_active"),
    ]

    operations = [
        migrations.RenameField(
            model_name="treatment",
            old_name="precautions",
            new_name="faqs",
        ),
    ]
