# Generated by Django 5.2.4 on 2025-08-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment_app", "0004_rename_precautions_treatment_faqs"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatment",
            name="cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="treatment",
            name="duration_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="duration_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="treatment",
            name="insurance_coverage",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="treatment",
            name="requires_anesthesia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="treatment",
            name="requires_room",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="treatment",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=20,
            ),
        ),
    ]
