# Generated by Django 5.2.4 on 2025-08-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("treatment_app", "0005_treatment_cost_treatment_duration_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="treatmentcategory",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
