# Generated by Django 5.2.4 on 2025-07-30 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("doctor_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("review_text", models.TextField()),
                ("rating", models.PositiveSmallIntegerField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="review_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("diagnosis", models.CharField(blank=True, max_length=100, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="doctor_app.doctor",
                    ),
                ),
            ],
        ),
    ]
