# Generated by Django 5.2.4 on 2025-07-30 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_app", "0002_specializationicon_remove_doctor_certifications_and_more"),
        ("review_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=100)),
                (
                    "reviewer_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="reviewer_pictures/"
                    ),
                ),
                ("review_text", models.TextField()),
                ("rating", models.FloatField(default=0.0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_reviews",
                        to="doctor_app.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
