# Generated by Django 5.2.4 on 2025-07-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("specialization", models.CharField(max_length=100)),
                ("qualification", models.CharField(max_length=100)),
                ("education", models.CharField(blank=True, max_length=255)),
                ("certifications", models.TextField(blank=True)),
                ("experience_years", models.PositiveIntegerField()),
                ("contact_number", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile_picture",
                    models.ImageField(blank=True, null=True, upload_to="doctors/"),
                ),
                (
                    "icon",
                    models.ImageField(blank=True, null=True, upload_to="doctor_icons/"),
                ),
                ("bio", models.TextField(blank=True)),
                ("clinic_address", models.TextField(blank=True)),
                ("available_days", models.CharField(blank=True, max_length=100)),
                ("available_time_start", models.TimeField(blank=True, null=True)),
                ("available_time_end", models.TimeField(blank=True, null=True)),
                ("rating", models.FloatField(default=0.0)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
