# Generated by Django 5.2.4 on 2025-08-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor_app", "0002_specializationicon_remove_doctor_certifications_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="status",
            field=models.CharField(default="active", max_length=20),
        ),
    ]
